# fly.toml - Configuration pour ton serveur MCP Node.js
app = "mcp-server-k-kwnq"  # ⚠️ LE NOM EXACT DE TON APP (PAS .fly, PAS .dev)

primary_region = "cdg"  # Paris (tu peux changer selon ta localisation)

[build]
  # Fly.io détecte automatiquement Node.js via le Dockerfile
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
